// Package shared provides common utilities, data structures, and logging mechanisms
// used across different components of the GoFortify application.
package shared

import (
	"fmt"
	"time"
)

// LogChan is a channel for passing logs from the server/vulnerabilities to the TUI.
var LogChan = make(chan string, 100)

// Logger is a thin wrapper that redirects all log output to the LogChan channel.
// This allows the TUI to capture and display logs generated by background routines.
type Logger struct{}

// NewLogger creates and returns a new instance of Logger.
func NewLogger() *Logger {
	return &Logger{}
}

// Println formats using default formats, appends a newline, and sends to LogChan.
func (l *Logger) Println(v ...interface{}) {
	LogChan <- fmt.Sprintln(v...)
}

// Printf formats according to a format specifier and sends to LogChan.
func (l *Logger) Printf(format string, v ...interface{}) {
	LogChan <- fmt.Sprintf(format, v...)
}

// Vulnerability represents a common structure for vulnerability logs.
type Vulnerability struct {
	Ip    string    `json:"ip"`
	Key   string    `json:"key"`
	Value string    `json:"value"`
	Time  time.Time `json:"time"`
	Path  string    `json:"path"`
}

// RateLimitLog represents a log entry for rate limiting.
type RateLimitLog struct {
	Ip     string    `json:"ip"`
	Path   string    `json:"path"`
	Method string    `json:"method"`
	Time   time.Time `json:"time"`
	Reason string    `json:"reason"`
}
